import type { Course } from "./types"

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Complete React Development Course",
    description:
      "Master React from basics to advanced concepts including hooks, context, and modern patterns. Build real-world projects and learn industry best practices.",
    shortDescription: "Learn React from scratch with hands-on projects and real-world examples.",
    price: 89.99,
    originalPrice: 129.99,
    thumbnail: "/react-development-course.png",
    instructor: {
      id: "inst1",
      name: "Sarah Johnson",
      avatar: "/female-instructor-avatar.png",
      bio: "Senior Frontend Developer with 8+ years experience",
    },
    category: "Web Development",
    level: "intermediate",
    duration: "12 hours",
    lessonsCount: 45,
    studentsCount: 2847,
    rating: 4.8,
    reviewsCount: 324,
    tags: ["React", "JavaScript", "Frontend", "Hooks"],
    isPublished: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "2",
    title: "Node.js & Express Backend Mastery",
    description:
      "Build scalable backend applications with Node.js and Express. Learn about APIs, databases, authentication, and deployment strategies.",
    shortDescription: "Master backend development with Node.js, Express, and modern tools.",
    price: 79.99,
    originalPrice: 99.99,
    thumbnail: "/nodejs-backend.png",
    instructor: {
      id: "inst2",
      name: "Michael Chen",
      avatar: "/male-instructor-avatar.png",
      bio: "Full-stack developer and tech lead",
    },
    category: "Backend Development",
    level: "intermediate",
    duration: "10 hours",
    lessonsCount: 38,
    studentsCount: 1923,
    rating: 4.7,
    reviewsCount: 256,
    tags: ["Node.js", "Express", "API", "Backend"],
    isPublished: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "3",
    title: "Python for Data Science",
    description:
      "Learn Python programming for data analysis, visualization, and machine learning. Work with pandas, numpy, matplotlib, and scikit-learn.",
    shortDescription: "Master Python for data analysis and machine learning applications.",
    price: 94.99,
    thumbnail: "/python-data-science-course.png",
    instructor: {
      id: "inst3",
      name: "Dr. Emily Rodriguez",
      avatar: "/female-data-scientist-avatar.png",
      bio: "Data Scientist with PhD in Statistics",
    },
    category: "Data Science",
    level: "beginner",
    duration: "15 hours",
    lessonsCount: 52,
    studentsCount: 3421,
    rating: 4.9,
    reviewsCount: 445,
    tags: ["Python", "Data Science", "Machine Learning", "Pandas"],
    isPublished: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-02-25"),
  },
  {
    id: "4",
    title: "UI/UX Design Fundamentals",
    description:
      "Learn the principles of user interface and user experience design. Master design tools, prototyping, and user research methodologies.",
    shortDescription: "Master UI/UX design principles and create stunning user experiences.",
    price: 69.99,
    originalPrice: 89.99,
    thumbnail: "/ui-ux-design-course.png",
    instructor: {
      id: "inst4",
      name: "Alex Thompson",
      avatar: "/diverse-designer-avatars.png",
      bio: "Senior UX Designer at top tech companies",
    },
    category: "Design",
    level: "beginner",
    duration: "8 hours",
    lessonsCount: 32,
    studentsCount: 1654,
    rating: 4.6,
    reviewsCount: 198,
    tags: ["UI Design", "UX Design", "Figma", "Prototyping"],
    isPublished: true,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "5",
    title: "Advanced JavaScript & TypeScript",
    description:
      "Deep dive into advanced JavaScript concepts and TypeScript. Learn about async programming, design patterns, and modern ES6+ features.",
    shortDescription: "Master advanced JavaScript and TypeScript for professional development.",
    price: 84.99,
    thumbnail: "/advanced-javascript-typescript.png",
    instructor: {
      id: "inst5",
      name: "David Kim",
      avatar: "/male-developer-avatar.png",
      bio: "JavaScript expert and conference speaker",
    },
    category: "Programming",
    level: "advanced",
    duration: "14 hours",
    lessonsCount: 48,
    studentsCount: 2156,
    rating: 4.8,
    reviewsCount: 287,
    tags: ["JavaScript", "TypeScript", "Advanced", "ES6+"],
    isPublished: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-02-18"),
  },
  {
    id: "6",
    title: "Mobile App Development with React Native",
    description:
      "Build cross-platform mobile applications using React Native. Learn navigation, state management, and native device features.",
    shortDescription: "Create mobile apps for iOS and Android using React Native.",
    price: 99.99,
    originalPrice: 139.99,
    thumbnail: "/react-native-mobile-development.png",
    instructor: {
      id: "inst6",
      name: "Lisa Wang",
      avatar: "/female-mobile-developer-avatar.png",
      bio: "Mobile development specialist",
    },
    category: "Mobile Development",
    level: "intermediate",
    duration: "16 hours",
    lessonsCount: 55,
    studentsCount: 1789,
    rating: 4.7,
    reviewsCount: 234,
    tags: ["React Native", "Mobile", "iOS", "Android"],
    isPublished: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-02-22"),
  },
]

export const categories = [
  "All Categories",
  "Web Development",
  "Backend Development",
  "Data Science",
  "Design",
  "Programming",
  "Mobile Development",
]

export const levels = ["All Levels", "beginner", "intermediate", "advanced"]
